### ISSUE TITLE
Add rapidsai and rapidsai-nightly channels

### ISSUE THREAD

**Issue by seibert** [ContinuumIO/anaconda-package-data#16]
Request from @jakirkham on behalf of the RAPIDS team.

**Comment by sophiamyang** [comment]
Added rapidsai and rapidsai-nightly channels

**Comment by jakirkham** [comment]
Thank you! 😀

cc @datametrician

**Comment by jakirkham** [comment]
So I tried running this, but am not seeing anything. Though this could totally be user error. Pointers would be welcome 🙂

```
$ condastats overall --monthly --data_source rapidsai cudf
Series([], Name: counts, dtype: int64)
```

**Comment by sophiamyang** [comment]
I only updated the hourly files, which are used in this repo. `condastats` is using the summarized monthly data files, which have not been updated yet.  I will update the monthly files today .

**Comment by jakirkham** [comment]
Thanks Sophia! Please let us know when you need us to try things out again 😉

**Comment by sophiamyang** [comment]
Updated the monthly files. Please try again! 🙂

**Comment by jakirkham** [comment]
Looks good. Thanks for your help Sophia! 😄

```
$ condastats overall --monthly --data_source rapidsai cudf
pkg_name  time   
cudf      2018-10      93.0
          2018-11    1038.0
          2018-12     807.0
          2019-01    1503.0
          2019-02    2702.0
          2019-03    4586.0
          2019-04    5245.0
          2019-05    4576.0
          2019-06    3470.0
          2019-07    5546.0
          2019-08    2825.0
          2019-09    2244.0
          2019-10    3330.0
          2019-11    2669.0
          2019-12    2129.0
Name: counts, dtype: float64
```

**Comment by datametrician** [comment]
@sophiamyang @jakirkham those seem like only stable, shouldn't nightlies be included?

**Comment by datametrician** [comment]
Nevermind, if you remove rapidsai it includes both stable and nightly, thanks everyone

**Comment by jakirkham** [comment]
Yeah you can also select the nightlies specifically if you want to break them out.

```
$ condastats overall --monthly --data_source rapidsai-nightly cudf
pkg_name  time   
cudf      2019-02       19.0
          2019-03     2538.0
          2019-04     1874.0
          2019-05     8161.0
          2019-06    12589.0
          2019-07     6480.0
          2019-08    11840.0
          2019-09     6232.0
          2019-10     9025.0
          2019-11    13241.0
          2019-12     6453.0
Name: counts, dtype: float64
```

**Comment by sophiamyang** [comment]
That doesn't look right. I haven't included the `rapidsai-nightly` channel yet. Let me take a look.

**Comment by sophiamyang** [comment]
Right I did include both rapidsai and rapidsai-nightly channels.
