### ISSUE TITLE
RuntimeError: Decompression 'SNAPPY' not available.  Options: ['GZIP', 'UNCOMPRESSED']

### ISSUE THREAD

**Issue by CJ-Wright** [ContinuumIO/anaconda-package-data#17]
I ran into `RuntimeError: Decompression 'SNAPPY' not available.  Options: ['GZIP', 'UNCOMPRESSED']` while using the binder notebook in this repo.

**Comment by sophiamyang** [comment]
I added `python-snappy` in the environment.yml file. The binder notebook should work now. Let me know if you still see any issues. Thanks!
