### ISSUE TITLE
Anaconda for Linux Mint

### ISSUE THREAD

**Issue by boatjones** [ContinuumIO/anaconda-package-data#18]
Installing anaconda on a Linux Mint OS (a distro based on Ubuntu) runs into problems due to the missing keyword "linuxmint" in vscode.py when looking for the OS type.  Presently, only "debian" and "ubuntu" are listed in this file for that branch of Linux distros using deb package managers.  As a result, running anaconda-navigator fails absent this keyword.

The file supplied has the additions needed for Linux Mint.  It runs perfectly.  Location:
~/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/external_apps/vscode.py
[vscode.py.zip](https://github.com/ContinuumIO/anaconda-package-data/files/4910520/vscode.py.zip)

**Comment by seibert** [comment]
Hi, this repo is for download data of Anaconda packages.  To report issues with Anaconda itself, you should file an issue at: https://github.com/ContinuumIO/anaconda-issues

Thanks!
