### ISSUE TITLE
Add nvidia channel

### ISSUE THREAD

**Issue by DMOanalytics** [ContinuumIO/anaconda-package-data#19]
Can we please add nvidia channel (https://anaconda.org/nvidia) so we can get download stats for all packages within?
Currently, I don't see any download counts using condastats.

**Comment by seibert** [comment]
Yes, I will add that into the next data build, which is running a bit behind but should happen this week.

**Comment by seibert** [comment]
I have added the `nvidia` channel to June and July 2021 data.  We will add it to older months during a future reprocessing.
