### ISSUE TITLE
How could I get the last month data?

### ISSUE THREAD

**Issue by mszhanyi** [ContinuumIO/anaconda-package-data#20]
It looks I could only get the data from 3 months ago.
How could I get last month data?

condastats overall condastats --start_month 2021-01 --end_month 2021-05 --monthly
![image](https://user-images.githubusercontent.com/16190118/128459727-afa2c87c-3f90-4db4-b6e3-44c494fdbd36.png)

condastats overall condastats --start_month 2021-01 --end_month 2021-06 --monthly
![image](https://user-images.githubusercontent.com/16190118/128459784-ac88cf2f-2360-4869-9201-bf80f262fbe7.png)

**Comment by seibert** [comment]
We're running a bit behind on processing.  We should be caught up next week.

**Comment by seibert** [comment]
June and July 2021 data has been uploaded
