### ISSUE TITLE
Access Issue with April 2023 files.

### ISSUE THREAD

**Issue by rshah-coatue** [ContinuumIO/anaconda-package-data#40]
We are facing access issues while accessing March data files from below s3 path.

`s3://anaconda-package-data/conda/hourly/2023/03/`

Error: `fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden`

**Comment by rshah-coatue** [comment]
Thank you. We are again experiencing the same issue with April Data.

`[s3://anaconda-package-data/conda/hourly/2023/04/](s3://anaconda-package-data/conda/hourly/2023/04/2023-04-28.parquet)`

Error: `An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied`

**Comment by cappadona** [comment]
Hi @rshah-coatue. Apologies for the inconvenience. You should be able to access the April data now. Thanks for reporting this.
