### ISSUE TITLE
Download counts missing python 3.10+ versions

### ISSUE THREAD

**Issue by jezdez** [ContinuumIO/anaconda-package-data#41]
Originally filed in https://github.com/conda/infrastructure/issues/660

**Comment by jezdez** [comment]
Just removed .conda from this topic since there is also #45

**Comment by jezdez** [comment]
According to @cappadona this was fixed

**Comment by wolfv** [comment]
Awesome! I'll try it out

**Comment by jakirkham** [comment]
This is really exciting. Thanks Jannis! 🙏

Curious to hear what you find Wolf 🙂
