### ISSUE TITLE
Add PyTorch channels to the anaconda-package-data repo

### ISSUE THREAD

**Issue by atalman** [ContinuumIO/anaconda-package-data#42]
Hello Anaconda team. We would like to retrieve anaconda download statistics for PyTorch packages.
For this we would need to add following channels to the anaconda-package-data repo:
pytorch : https://anaconda.org/pytorch/
pytorch-test : https://anaconda.org/pytorch-test/

This way we can query it using condastats package.

**Comment by seibert** [comment]
Hi, do you also want pytorch-nightly?

**Comment by atalman** [comment]
hi @seibert . No we only want pytorch and pytorch-test
nightly channel is getting new binaries (and old binaries wiped out) every night. At this point 
1. pytorch channel - critical to have
2. pytorch-test channel - nice to have

**Comment by seibert** [comment]
Hi, I've added these two channels to the dataset going back to 2023-01-01.  Let me know if you need the data further back in time.
