### ISSUE TITLE
Missing packages?

### ISSUE THREAD

**Issue by jamesmunro** [ContinuumIO/anaconda-package-data#49]
Hi,

Is there some threshold or rule for inclusion in the stats?  The package I'm looking for but can't find is conda-forge/arcticdb. 
https://anaconda.org/conda-forge/arcticdb

The package page says 50k downloads but I can't find it in the monthly parquet files.

Thanks,

**Comment by jaimergp** [comment]
You are probably hitting #45. `arcticdb` never had `.tar.bz2` artifacts.

**Comment by cappadona** [comment]
Thanks @jaimergp.

* Just posted a status update on https://github.com/ContinuumIO/anaconda-package-data/issues/45#issuecomment-1877517341

> We're working on finalizing a new pipeline that will source this public data set and include `.conda` packages moving forward. We expect to have it ready by the end of March 2024 and will post an update here when it is available.

**Comment by jamesmunro** [comment]
Ah, thank you.  That would explain it.  I'll close this.
