### ISSUE TITLE
Missing Monthly Package files from November 2023.

### ISSUE THREAD

**Issue by rshah-coatue** [ContinuumIO/anaconda-package-data#50]
We don't see any new package files uploaded after October 2023. 

`aws s3 ls s3://anaconda-package-data/conda/hourly/2023/`

<img width="393" alt="image" src="https://github.com/ContinuumIO/anaconda-package-data/assets/87651260/0426872f-8151-4d43-a5d8-ab8bc5ff879e">

**Comment by cappadona** [comment]
Hi @rshah-coatue. Thanks for reporting this. November 2023 data is now available in the bucket. 

December 2023 data is still being processed by an upstream pipeline and should be available before the end of the week.

**Comment by rshah-coatue** [comment]
> Hi @rshah-coatue. Thanks for reporting this. November 2023 data is now available in the bucket.
> 
> December 2023 data is still being processed by an upstream pipeline and should be available before the end of the week.

Thanks much @cappadona.  Please keep me posted when December Data is available. Really Appreciated.

**Comment by cappadona** [comment]
No worries, @rshah-coatue. December 2023 data is now available in the bucket as well. Thanks for your patience and understanding 🙏🏼.

**Comment by rshah-coatue** [comment]
Thank you very much for the update @cappadona.
