### ISSUE TITLE
Add missing March data

### ISSUE THREAD

**Issue by jezdez** [ContinuumIO/anaconda-package-data#51]
It seems as if there isn't a Parquet file for March (yet?): https://s3.amazonaws.com/anaconda-package-data/conda/monthly/2024/2024-03.parquet

**Comment by jakirkham** [comment]
Think we are waiting for the `.conda` data ( https://github.com/ContinuumIO/anaconda-package-data/issues/45#issuecomment-2029783843 )

It sounded like we might be close last week. Asked for an update here ( https://github.com/ContinuumIO/anaconda-package-data/issues/45#issuecomment-2060211168 ), but haven't heard back

**Comment by rshah-coatue** [comment]
Any updates here?

**Comment by modouldemba** [comment]
Yes March data is still unavailable. Any updates?

**Comment by phwuil** [comment]
+1
What is the problem that explains the inaccessibility of March data?

Thanks a lot for this work !

**Comment by cappadona** [comment]
Hi all. March (and April) data is now available in the bucket.

* more details in #45

**Comment by jezdez** [comment]
Closing..
