### ISSUE TITLE
Access denied when trying to load 2019 data

### ISSUE THREAD

**Issue by ofajardo** [ContinuumIO/anaconda-package-data#9]
when running this (both from binder and in my own conda environment, python 3.7, both on windows and linux):

```
cat = intake.open_catalog('https://raw.githubusercontent.com/ContinuumIO/anaconda-package-data/master/catalog/anaconda_package_data.yaml')
df = cat.anaconda_package_data_by_year(year=2019).to_dask()

```
I get the following error:

```
ClientError: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
```

This used to work one month ago or so. ANy ideas of what's wrong?
It seems to work fine if I say year=2018.

Thanks!

**Comment by sophiamyang** [comment]
Sorry I forgot to change the permission when I upload the new data. Try it again and let me know if you see more issues. Thanks!

**Comment by ofajardo** [comment]
it works! thanks!
